# Site settings
title: IndieSense - Candid Indie Game Reviews
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Find high quality indie game reviews to read and animated gifs and screenshots to discover new and exciting indie games!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://indiesense.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
permalink: :categories/:title
# Build settings
markdown: kramdown
gems:
  - jekyll-sitemap